services:
  etcd:
    image: bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/bitnami/etcd

  postgres1:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg1_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres2:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg2_data:/var/lib/postgresql/data
    ports:
      - "5434:5433"

volumes:
  etcd_data:
  pg1_data:
  pg2_data: