version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd
    environment:
      ETCDCTL_API: "3"
      ETCD_NAME: "etcd0"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
    networks:
      - db-cluster

  patroni1:
    image: zalando/patroni
    environment:
      PATRONI_NAME: "postgres1"
      PATRONI_POSTGRESQL_DATA_DIR: "/var/lib/postgresql/data/pgdata"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni1:5432"
      PATRONI_ETCD_URL: "http://etcd:2379"
      PATRONI_REPLICATION_USERNAME: "replicator"
      PATRONI_REPLICATION_PASSWORD: "secret"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - db-cluster

  patroni2:
    image: zalando/patroni
    environment:
      PATRONI_NAME: "postgres2"
      PATRONI_POSTGRESQL_DATA_DIR: "/var/lib/postgresql/data/pgdata"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni2:5432"
      PATRONI_ETCD_URL: "http://etcd:2379"
      PATRONI_REPLICATION_USERNAME: "replicator"
      PATRONI_REPLICATION_PASSWORD: "secret"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - db-cluster

  haproxy:
    image: haproxy
    ports:
      - "5432:5432"  # PostgreSQL
      - "8008:8008"  # Patroni API
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - db-cluster

networks:
  db-cluster:

volumes:
  pgdata1:
  pgdata2: