services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/bitnami/etcd

  patroni1:
    image: docker.io/zalando/spilo-16:3.0-p1
    environment:
      - SCOPE=cluster
      - ETCD_ENDPOINTS=http://etcd:2379
      - PG_LISTEN=0.0.0.0:5432
    volumes:
      - patroni1_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      - etcd

  patroni2:
    image: docker.io/zalando/spilo-16:3.0-p1
    environment:
      - SCOPE=cluster
      - ETCD_ENDPOINTS=http://etcd:2379
      - PG_LISTEN=0.0.0.0:5433
    volumes:
      - patroni2_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    depends_on:
      - etcd

  haproxy:
    image: haproxy:2.8
    ports:
      - "7000:7000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - patroni1
      - patroni2

volumes:
  etcd_data:
  patroni1_data:
  patroni2_data: