global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'motospark-backend'
    static_configs:
      - targets: ['backend:5000']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']